Verbose

diff --git a/services/dreambooth/Dockerfile b/services/dreambooth/Dockerfile
--- a/services/dreambooth/Dockerfile
+++ b/services/dreambooth/Dockerfile
@@ -1,61 +1,62 @@
 # syntax=docker/dockerfile:1
 
-FROM brandnewx/ubuntu22:cuda-pytorch as download
-#FROM brandnewx/ubuntu22:full as download
-USER root
-SHELL ["/bin/bash", "-ceuxo", "pipefail"]
-WORKDIR /
+# Commented out as entrypoint.sh can now download and cache HF models.
+# FROM brandnewx/ubuntu22:cuda-pytorch as download
+# #FROM brandnewx/ubuntu22:full as download
+# USER root
+# SHELL ["/bin/bash", "-ceuxo", "pipefail"]
+# WORKDIR /
 
-ARG HF_TOKEN
-ARG HF_SD_REPO="runwayml/stable-diffusion-v1-5"
-ARG HF_VAE_REPO="stabilityai/sd-vae-ft-mse" 
+# ARG HF_TOKEN
+# ARG HF_SD_REPO="runwayml/stable-diffusion-v1-5"
+# ARG HF_VAE_REPO="stabilityai/sd-vae-ft-mse" 
 
-RUN apt-get update -q && apt-get install -y git git-lfs && apt-get clean
+# RUN apt-get update -q && apt-get install -y git git-lfs && apt-get clean
 
-# Download model
-RUN <<EOF
-if [ -z "${HF_TOKEN}" ]; then
-    echo "HF_TOKEN not specified."
-    return 1
-fi
+# # Download model
+# RUN <<EOF
+# if [ -z "${HF_TOKEN}" ]; then
+#     echo "HF_TOKEN not specified."
+#     return 1
+# fi
 
-echo "Downloading SD model (Unet and Text Encoder)..."
-mkdir -p /content/model
-cd /content/model
-git init .
-git lfs install --system --skip-repo
-git remote add -f origin "https://USER:${HF_TOKEN}@huggingface.co/${HF_SD_REPO}"
-git config core.sparsecheckout true
-echo -e "feature_extractor\nsafety_checker\nscheduler\ntext_encoder\ntokenizer\nunet\nvae\nmodel_index.json" > .git/info/sparse-checkout
-git pull origin main
-rm -rf ./.git
-EOF
+# echo "Downloading SD model (Unet and Text Encoder)..."
+# mkdir -p /content/model
+# cd /content/model
+# git init .
+# git lfs install --system --skip-repo
+# git remote add -f origin "https://USER:${HF_TOKEN}@huggingface.co/${HF_SD_REPO}"
+# git config core.sparsecheckout true
+# echo -e "feature_extractor\nsafety_checker\nscheduler\ntext_encoder\ntokenizer\nunet\nvae\nmodel_index.json" > .git/info/sparse-checkout
+# git pull origin main
+# rm -rf ./.git
+# EOF
 
-RUN <<EOF
-if [ ! -f '/content/model/unet/diffusion_pytorch_model.bin' ]; then
-    echo "Make sure you accepted the terms in https://huggingface.co/${HF_SD_REPO}"
-    return 2
-fi
-EOF
+# RUN <<EOF
+# if [ ! -f '/content/model/unet/diffusion_pytorch_model.bin' ]; then
+#     echo "Make sure you accepted the terms in https://huggingface.co/${HF_SD_REPO}"
+#     return 2
+# fi
+# EOF
 
-RUN <<EOF
-# Optionally download and replace VAE
-if [ ! -z "${HF_VAE_REPO}" ]; then
-    echo "Downloading alternative VAE..."
-    rm -rf /content/model/vae
-    mkdir -p /content/model/vae
-    cd /content/model/vae
-    git clone "https://USER:${HF_TOKEN}@huggingface.co/${HF_VAE_REPO}" .
-    rm -rf ./.git
-fi
-EOF
+# RUN <<EOF
+# # Optionally download and replace VAE
+# if [ ! -z "${HF_VAE_REPO}" ]; then
+#     echo "Downloading alternative VAE..."
+#     rm -rf /content/model/vae
+#     mkdir -p /content/model/vae
+#     cd /content/model/vae
+#     git clone "https://USER:${HF_TOKEN}@huggingface.co/${HF_VAE_REPO}" .
+#     rm -rf ./.git
+# fi
+# EOF
 
-RUN <<EOF
-if [ ! -f "/content/model/vae/diffusion_pytorch_model.bin" ]; then
-    echo "VAE model is missing!"
-    return 3
-fi
-EOF
+# RUN <<EOF
+# if [ ! -f "/content/model/vae/diffusion_pytorch_model.bin" ]; then
+#     echo "VAE model is missing!"
+#     return 3
+# fi
+# EOF
 
 
 FROM brandnewx/ubuntu22:cuda-pytorch
@@ -66,8 +67,8 @@ WORKDIR /
 
 RUN apt-get update -q && apt-get install -y git git-lfs && apt-get clean
 
-# Copy default model
-COPY --from=download /content/model /content/model
+## Copy default model
+# COPY --from=download /content/model /content/model
 
 # Install xformers
 COPY --from=brandnewx/xformers /xformers-dist /xformers-dist
